apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  annotations:
    resource.twingate.com: "true"
    resource.twingate.com/alias: "uptime.int"
spec:
  selector:
    app: uptime-kuma
  ports:
    - port: 80
      targetPort: 3001
  type: ClusterIP
