apiVersion: v1
kind: Service
metadata:
  name: nginx-basic
  annotations:
    resource.twingate.com: "true"
    resource.twingate.com/alias: "nginx.int"
spec:
  selector:
    app: nginx-basic
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
