apiVersion: v1
kind: Service
metadata:
  name: nginx-basic
  namespace: web
  annotations:
    resource.twingate.com: "true"
    resource.twingate.com/alias: "nginx.int"
spec:
  selector:
    app: nginx-basic
  ports:
    - port: 8080
      targetPort: 80
  type: ClusterIP
